In [26]:
from numpy import array, matmul

# Classical Information

Consider a system X with finite classical states. 
Let $\Sigma$ be the set of classical states. i.e 
* X is a bit then $\Sigma = {0, 1}$
* X is a die then $\Sigma = {1, 2, 3, 4, 5, 6}$
Consider the case when X is a bit with $P(x = 0) = \frac{3}{4}$ and $P(x = 1) = \frac{1}{4}$ We can notate this instead as
 $\begin{pmatrix}
 \frac{3}{4}\\
 \frac{1}{4}
 \end{pmatrix}$

 ### Dirac Notation Part 1
Let $\Sigma$ be a classical state set and assume $\Sigma$ is ordered in correspondence with the integers $1, ..., |\Sigma|$
<br></br>
We denote by **$|a\rangle$ (ket a)** to be the column vector corresponding to $a \in \Sigma$ with 0 for all other entries.
<br></br>
For Example for $\Sigma = {0, 1}$ then
$$
    |0\rangle = \begin{bmatrix}
 1\\
 0
 \end{bmatrix} 
$$
and
$$
 |1\rangle = \begin{bmatrix}
 0\\
 1
 \end{bmatrix}
$$
The vectors described by ket notation are **standard basis vectors**. Every vector can be uniquely described as a linear combination of standard basis vectors. Using the example above we can write
$$
 \begin{pmatrix}
 \frac{3}{4}\\
 \frac{1}{4}
 \end{pmatrix} =
 \frac{3}{4}|0\rangle + \frac{1}{4}|1\rangle
$$

In [63]:
ket0 = array([[1, 0]]).T
ket1 = array([[0, 1]]).T
prob_vector = (3/4)*ket0 + (1/4)*ket1
print(prob_vector)

[[0.75]
 [0.25]]


### Measuring probablistic States
By *measure* we mean we check the value of a classical state. 

Suppose we see classical state $a \in \Sigma$. Then we know $$P(X = a) = 1$$

This is represented by $\ket{a}$. So measuring *collapses* the probabilistic states into basis vectors.

### Deterministic Operations
The outcome depends entirely on the state of the system. I.e there is no randomness. In math we say

Every function $f: \Sigma \to \Sigma$ describes a *determinitstic operation* that transforms the classical state $a$ into $f(a)$ for each $a \in \Sigma$

Given any function $f: \Sigma \to \Sigma$ there is a unique matrix $M$ satisfying for all $a \in \Sigma$
$$
M\ket{a} = \ket{f(a)}
$$
where
$$
M(b, a) = \begin{cases} 
    1 & b = f(a)\\
    0 & b \ne f(a)
    \end{cases}
$$
This matrix has exactly one 1 in each column and 0 in all other entries. This allows us to describe the action of an operation by *matrix-vector multiplication* 
$$
v \mapsto Mv
$$
For example consider $\Sigma = {0, 1}$ there are 4 functions of the form $f: \Sigma \to \Sigma$:
* $f_1$: $f_1(0) = 0$ and $f_1(1) = 0$ **This is the zero function** Becomes $
 M_1 = \begin{pmatrix}
 1 & 1\\
 0 & 0
 \end{pmatrix}$
 because $M_1[0, 0] = 1$ because $f(0) = 0$. and $M_1[0, 1] = 1$ because $f(1) = 0$. 
* $f_2$: $f_2(0) = 0$ and $f_2(1) = 1$ **This is the identity function** Becomes $
 M_2 = \begin{pmatrix}
 1 & 0\\
 0 & 1
 \end{pmatrix}$
* $f_3$: $f_3(0) = 1$ and $f_3(1) = 0$ **The Not function or bit-flip** Becomes $
 M_3 = \begin{pmatrix}
 0 & 1\\
 1 & 0
 \end{pmatrix}$
* $f_4$: $f_4(0) = 1$ and $f_4(1) = 1$ **The One function** Becomes $
 M_4 = \begin{pmatrix}
 0 & 0\\
 1 & 1
 \end{pmatrix}$


In [88]:
m1 = array([[1, 1], [0, 0]])
m2 = array([[1, 0], [0, 1]])
m3 = array([[0, 1, ], [1, 0]])
m4 = array([[0, 0], [1, 1]])
matmul(m4, ket0)


array([[0],
       [1]])

### Dirac Notation (Part II)
We denote $\bra{a}$ as the **row vector** having 1 in the entry corresponding to $a \in \Sigma$, with 0 for all other entries.
Note: A row vector times a column vector creates a single value (generally the dot product more generally called an *inner product*).
So we can write 
$$
\braket{a|b} = \begin{cases}
 1 & a = b \\
 0 & a \ne b
\end{cases}
$$

A column by a row vector gives us a matrix so for binary alphabet we get a few exampels
$$
\ket{0}\bra{1} = \begin{pmatrix}1\\0\end{pmatrix}\begin{pmatrix}1&&0\end{pmatrix} = 
\begin{pmatrix}
0 & 1\\
0 & 0
\end{pmatrix}
$$
We see more generally the matrix produced by $\ket{a}\bra{b}$ has a 1 in the $a, b$ position and a 0 everywhere else.


In [70]:
bra0 = array([[1, 0]])
bra1 = array([[0, 1]])
matmul(ket1, bra1) # ket time bra makes a matrix

array([[0, 0],
       [0, 1]])

### Deterministic Operations
We can express each matrix $M$ as 
$$
M = \sum_{b\in\Sigma}\ket{f(b)}\bra{b}
$$
Thus we know on standard basis vectors we get
$$
M\bra{a} = (\sum_{b\in\Sigma}\ket{f(b)}\bra{b})\bra{a} = \sum_{b\in\Sigma}\ket{f(b)}\braket{b|a}
$$
Then because the zeros shown above this simplifies to 
$$
M\bra{a} = \sum_{b\in\Sigma}\ket{f(b)}\braket{b|a} = \ket{f(a)}
$$

In [73]:
matmul(ket0, bra0)

array([[1, 0],
       [0, 0]])

### Probabilistic Operations
*Probabilistic operations* are classical operations that may introduce randomness or uncertainty. Ex on a bit
* If state is 0 do nothing
* If state is 1 then flip with probability $\frac{1}{2}$

These operations are represented by *stochastic matrices*: 
* All entries are nonnegative real numbers
* The entries in every column sum to 1
* So every column creates a probability vector.
For our example we get
$$
\begin{pmatrix}
1 & \frac{1}{2}\\
0 & \frac{1}{2}
\end{pmatrix}
$$
Note that any probabilistic operation can be thought of as a collection of deterministic operations. For example
$$
\begin{pmatrix}
1 & \frac{1}{2}\\
0 & \frac{1}{2}
\end{pmatrix} = 
\frac{1}{2}\begin{pmatrix}
1 & 1\\
0 & 0
\end{pmatrix}
+ 
\frac{1}{2}\begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}
$$
So you can think of it as randomly choosing deterministic operations.

In [75]:
(1/2)*m1 + (1/2)*m2

array([[1. , 0.5],
       [0. , 0.5]])

### Composing Operations
Suppose X is a system and $M_1, ..., M_n$ are stochastic matrices. Assume we do $M_1$ on $v$ then $M_2$ on that result. We know Matrix multiplication is associative (not commutative so M_2 is preformed on M_1 since it is done first) so 
$$
M_2(M_1v) = (M_2M_1)v
$$
So the composition of all of them is $$M_n...M_1$$
Which becomes a new stochastic matrix since they are closed over multiplication.